POST http://localhost:3010/api/carts
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5YzJiOTRlZGQ0NDM4MTg2MWVhMzEiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NDY1MTg3MTN9.z-EbG7KsQfFv26Nuzmt_1ojRxjNPZCCS2D2jq7NTWII

{
  "email": "usmana@gmail.com",
  "phone": "9876543210",
  "items": [
    {
      "product_id": "6808d48db8d0431ece74c7c7",
      "color": "Brown",
      "size": 40,
      "qty": 2
    },
    {
      "product_id": "6809902ab8d0431ece74c7d0",
      "color": "Yellow",
      "size": 42,
      "qty": 1
    }
  ]
}
